name:                learning
version:             0.1.0.0
github:              "jotacib3/learning"
license:             BSD3
author:              "Juan José"
maintainer:          "jotacib3@gmail.com"
copyright:           "2022 Juan José"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jotacib3/learning#readme>

dependencies:
- base >= 4.7 && < 5
- matrix
- mtl >= 2.2.2
- random >= 1.1
- random-shuffle >= 0.0.4

library:
  source-dirs: src

executables:
  learning-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning

tests:
  learning-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning
